#!/usr/bin/env python3
import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def tweet():
    if len(sys.argv)!=2:
        sys.exit("Usage: ./smile word")
    
    screen_name = sys.argv[1].lstrip("@")
    screen_name = screen_name.lower()
    tweet_list = helpers.get_user_timeline(screen_name,50)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # analyze word
    for line in tweet_list:
        score = analyzer.analyze(line)
        if score > 0.0:
            print(colored("{} {}".format(score,line), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score,line), "red"))
        else:
            print(colored("{} {}".format(score,line), "yellow"))

    
    
if __name__=="__main__":
    tweet()